export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN"
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
export const SETUP_USER_ERROR = "SETUP_USER_ERROR"

export const DISPLAY_ALERT = "DISPLAY_ALERT"

export const CLOSE_ALERT = "CLOSE_ALERT"

export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR"

export const HANDLE_CHANGE = "HANDLE_CHANGE"

export const REMOVE_FILTERS = "REMOVE_FILTERS"

export const CHANGE_PAGE = "CHANGE_PAGE"
